### ISSUE TITLE
Offset Validation Nulls

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1071]
**Describe the bug**

ArrayDataBuilder performs various validation of the offsets array. In particular, it validates that offsets are monotonically increasing and within the bounds of the values array.

However, it is my understanding that nulls can have arbitrary offsets and so I think this might be overly strict?

**To Reproduce**

```
let offsets = vec![2, 0, 2, 2];
let validity = vec![false, true, false];
let values = "ab";

let mut offsets_buffer = MutableBuffer::new(offsets.len() * 4);
offsets_buffer.extend_from_slice(&offsets);

let validity_buffer = MutableBuffer::from_iter(validity.iter().cloned());

let mut values_buffer = MutableBuffer::new(values.len());
values_buffer.extend_from_slice(values.as_bytes());

let arraydata = ArrayDataBuilder::new(DataType::Utf8)
    .len(validity.len())
    .add_buffer(offsets_buffer.into())
    .add_buffer(values_buffer.into())
    .null_bit_buffer(validity_buffer.into())
    .build()
    .unwrap();
```

**Expected behavior**

I would expect this to not error, as the non-null elements have valid offsets

**Additional context**

I encountered this whilst trying to produce a reproducer for a related bug, where the string comparison kernels panic in the presence of non-monotonically increasing offsets. This in turn was whilst working on a parquet string array decoder, where I was hoping to just leave offsets for nulls zero-initialized.

**Comment by alamb** [comment]
I am not 100% sure if supporting non monotonic offsets is something we want to fix to be honest.  My rationale is if the offsets are monotonic, all arrays with offsets can calculate length as `offsets[i] - offsets[i-1]` which has better failure properties than if we ended up doing stuff like `0 - 32` or something because the offset had been left unset

Thus

Also for fun, I checked @jorgecarleitao 's implementation in arrow2 which also ensures that offsets are always monotonic. 
https://github.com/jorgecarleitao/arrow2/blob/37a9c758826a92d98dc91e992b2a49ce9724095d/src/array/specification.rs#L102-L119

I am pretty sure the C++ implementation also ensures the offsets are monotonic without first checking it is null: https://github.com/apache/arrow/blob/master/cpp/src/arrow/array/validate.cc#L568-L592

**Comment by tustvold** [comment]
Will not fix would be a perfectly valid outcome of this ticket :+1:

**Comment by alamb** [comment]
I agree the spec is somewhat vague in this respect: https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout

Perhaps I can ask on the dev mailing list for a clarification ...

**Comment by jorgecarleitao** [comment]
I think that in general the property we seek is: discarding the validity cannot result in UB when accessing the values. This justifies the values buffer of a primitive array is always initialized, and the offsets being valid and in-bounds even in null cases.

The rational for this is that sometimes it is faster to skip validity accesses and only iterate over the values (and clone the validity). I do not recall the benchmark result, but this may explain why string comparison ignores validity and `&` the bitmaps instead.

**Comment by alamb** [comment]
I created https://github.com/apache/arrow/pull/12019 to explicitly mention this case in the docs -- and we can iterate from there perhaps

**Comment by tustvold** [comment]
The consensus appears to be that offsets should be monotonically increasing, so closing this
