### ISSUE TITLE
`packed_simd` v.s. `portable_simd`, which should be used?

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1492]
**Describe your question**
I think this is an old question, but I don't find a clear answer. So need your help!
Something that I find is that, the crate `packed_simd` has been in maintenance mode and no new features will be introduced: https://github.com/rust-lang/packed_simd/issues/282#issuecomment-696506773
https://github.com/rust-lang/packed_simd/blob/master/README.md

Also, `protable_simd` is planned to be the stable and standard library in the future, it is true?

My questions are:
1. Is `packed_simd_2` still a reliable crate?
2. Do we need to migrate from `packed_simd_2` to `portable_simd`?
3. Which one could be stable in the future, `packed_simd_2` or `portable_simd`? 

I know these are old questions, but I don't find a clear answer. So need your help!

Re:
https://github.com/rust-lang/portable-simd/issues/170

**Comment by jhorstmann** [comment]
Both currently require a nightly compiler and it will probably take a while until portable_simd gets stabilized. Longer term we should switch to portable_simd as it will become the standard and there won't be any updates to packed_simd. As far as I know packed_simd currently has no major issues that would force us to switch.

Portable_simd has first class support for bitmasks, which fits the arrow data model for boolean and validity very well and could lead to some code simplification. On AVX512 capable CPUs that leads to slightly better code than [what we currently do manually](https://github.com/apache/arrow-rs/blob/c5442cf2fd8f046e6ad75d2d5c7efb2899dd654d/arrow/src/datatypes/numeric.rs#L144). On non-AVX512 machines the [code is currently worse](https://github.com/rust-lang/portable-simd/issues/264). For intel compatible targets that has [already been fixed in LLVM trunk](https://github.com/llvm/llvm-project/issues/53760), I think other architectures like arm neon or wasm are still affected. I don't actually know how good our current code simd works for arm or neon, but we should probably at least await the next llvm update in rust before we switch.

**Comment by HaoYang670** [comment]
Thanks for your answer @jhorstmann! Very much looking forward to the day when we can migrate to `std::simd`. I will close this issue.

**Comment by alamb** [comment]
I believe @jorgecarleitao did some work in arrow2 to migrate it away from using packed_simd (and thus no longer require nightly rust), which might be worth looking into: https://github.com/jorgecarleitao/arrow2/pull/747

**Comment by KonradHoeffner** [comment]
As of Rust nightly-1.78, packed_simd no longer works, see <https://github.com/rust-lang/packed_simd/issues/359>.

**Comment by alamb** [comment]
Update here is that arrow-rs does not use simd intrinsics anymore, and instead relies on the Rust compiler's (quite good) auto vectorization capabilities
