### ISSUE TITLE
Implement Extend for Builder

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1841]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The [FromIterator](https://doc.rust-lang.org/std/iter/trait.FromIterator.html) trait is a standard trait in the ecosystem for building a collection from an iterator. Supporting it within the builders would allow writing code like (not tested)

```
let strings = ["1", "2", "3"];

let array = strings
    .iter()
    .map(|s| Some(s.parse()?))
    .collect::<Result<Int32Builder>>()
    .unwrap()
    .finish();
```

**Describe the solution you'd like**

Implement FromIterator for the Builder types. In most cases FromIterator is implemented for the corresponding Array type, and so it should largely just be a case of moving this logic into the builder and making the array implementation call it.

**Describe alternatives you've considered**

We could not do this

**Comment by heyrutvik** [comment]
@tustvold I'm trying to understand the ticket. If I'm not wrong, `Extend` will provide us `extend` method and then we can extend an existing builder using an iterator.

Example,
```
let ints = [1, 2, 3];
let mut builder = Int32Builder::new(0);
builder.extend(ints.into_iter());
let array = builder.finish();
assert_eq!(3, array.len());
```
given that we have `impl Extend<i32> for Int32Builder` implemented. 

I'm confused because you mentioned `Extend` and not using any of its method in your example snippet. I believe `collect` is the main focus of your example which builds collection from an iterator. Could you please elaborate?

**Comment by tustvold** [comment]
Yes this is likely a brain fart on my part, the example should already be possible as we implement FromIterator. I think there is still value in implementing Extend, but perhaps less...

**Comment by heyrutvik** [comment]
Thanks @tustvold for the clarification. I started working on the ticket, and opened [a draft PR](https://github.com/apache/arrow-rs/pull/2038) for you to review to make sure whether I'm on the right direction or not. It adds `FromIterator` to `BooleanBuilder` and uses it in `BooleanArray` implementation. Once you confirm, I'll continue moving other existing `FromIterator` implementations.
