### ISSUE TITLE
Copy-On-Write Support to Support Mutating/Updating Arrays in Place

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1981]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Certain use-cases may benefit from being able to mutate arrays in place, without copying them. Fortunately we have most of the pieces to support this, it just requires some plumbing work.

**Describe the solution you'd like**

A high-level outline can be found below:

* Add COW conversion from `Buffer` to `MutableBuffer` likely using [`Arc::try_unwrap`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.try_unwrap)
* Add COW conversion from `T: Array` to their corresponding builder, i.e. `PrimitiveArray::into_builder`
* Add conversion from `ArrayRef` to `Arc<T>` - https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=abb7fcf97e33ba83d44b17f6c89e8f0b

It should then be possible to do something like (likely encapsulated in a nicer interface)

```
fn cow_builder(col: ArrayRef) -> Int32Builder {
    let col: Arc<Int32Array> = downcast_array(col).unwrap();
    let col: Int32Array = Arc::try_unwrap(col).unwrap_or_else(|_| col.as_ref().clone());
    col.into_builder()
}
```

**Additional context**

Arrow2 recently merged a form of support for this.

**Comment by alamb** [comment]
Related arrow2 code: Example https://github.com/jorgecarleitao/arrow2/blob/main/examples/cow.rs#L23

Looks like it was added by @jorgecarleitao in https://github.com/jorgecarleitao/arrow2/pull/1042 (which was a bit hard to find as it is described in terms of the implementation rather than the end user API change) 👍

**Comment by avantgardnerio** [comment]
Instead of copying-on-write (or maybe in addition to), how would we feel about an `AppendOnlyArrayBuilder` that never calls any method that would cause `MutableBuffer` to `realloc()` and move any pointers?

If we had that, we could have `AppendableRecordBatch`s, and a `borrow() -> &RecordBatch` (as opposed to `.finish()`) that would allow use to append (but not mutate) data, while still being able to do all the fun stuff we can do with `RecordBatch`es today (query in DataFusion, export to parquet, etc).

**Comment by tustvold** [comment]
I think that is a separate feature, would you mind creating a new issue along with the intended use-case? I suspect it concerns implementing some sort of append only memtable, something I have thoughts on having implemented something similar for IOx (spoiler mem copies are far from the bottleneck).

**Comment by avantgardnerio** [comment]
@tustvold @alamb @andygrove I filed an issue with PoC implementation: https://github.com/apache/arrow-rs/issues/3142

**Comment by viirya** [comment]
For COW, the high-level outline I think we have corresponding implementation now. Is there anything I miss?

**Comment by viirya** [comment]
For `into_buffer`, do you mean a `MutableBuffer` of a `ByteArray` so we can write `ByteArrayType` data into it?

**Comment by tustvold** [comment]
Sorry I meant into_builder for ByteArray

**Comment by alamb** [comment]
🎉  thank you @viirya  -- cc @avantgardnerio
