### ISSUE TITLE
Support extension arrays

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#218]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10258

This should include:
 * supporting the Arrow format
 * supporting field metadata

We can optionally:
 * support recognising known extensions (like UUID)

I'm mainly opening this up for wider visibility, I noticed that I was catching strays from metadata integration tests failing because Field doesn't support metadata :(

**Comment by alamb** [comment]
Comment from Andy Grove(andygrove) @ 2021-01-06T17:59:26.672+0000:
<pre>Removing fix version since this issue does not appear to be started yet</pre>

**Comment by rdettai** [comment]
@nevi-me: blast from the past! 😄 
- We support field metadata since https://github.com/apache/arrow/pull/9025
- What did you have in mind with "supporting the Arrow format" ? I don't really see what else we could do to materialize extension types within arrow-rs:
  - adding a new variant to the `DataType` enum would not be practical because downstream apps that want to handle the extension type as a built in logical type would need to explicitly unwrap it (or maybe that is precisely what we want!)
  - adding specific methods to `Field` such as `is_extention_type()` and/or `get_extension_type()`. Not a huge added value compared to just getting `ARROW:extension:name` out of the metadata.

**Comment by tustvold** [comment]
Closing this, as the existing extension type support is consistent with the C++ implementation
