### ISSUE TITLE
Parquet `WriterProperties.max_row_group_size` not wired up

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-rs#257]
**Describe the bug**
This property (that can be set via the `WriterPropertiesBuilder`):

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/file/properties.rs#L99

can only be retrieved using this getter:

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/file/properties.rs#L132-L135

but this getter is never used. In fact quickly trying out this property has no effect. I think it should probably we wired up here:

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/arrow/arrow_writer.rs#L80-L101

where the incoming `RecordBatch` is split into batches of the configured size that will then fed into individual record batches.

**To Reproduce**

1. create a `RecordBatch` with 3 rows.
2. Set `WriterProperties.max_row_group_size` to 1
3. Create a parquet file
4. See the that parquet file has only 1 row group (should be 3).

**Expected behavior**
Record batches created from arrow should respect `WriterProperties.max_row_group_size`.

**Additional context**
Commit in question is `508f25c10032857da34ea88cc8166f0741616a32`.

**Comment by nevi-me** [comment]
Thanks for noticing this @crepererum, it's related to https://github.com/apache/arrow-rs/issues/225, which is blocked by the inability to slice structs and lists correctly.

We want to use the slice facility to limit the row group sizes, i was thinking about this a few hours ago, that maybe we could track the offset and length in parquet instead of relying on arrow.
