### ISSUE TITLE
Update Arrow release process to include Rust and DataFusion commits, contributors, changes in release notes

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#274]
Bringing content from https://issues.apache.org/jira/browse/ARROW-12701,  so we have visibility in arrow-rs 

@ianmcook suggests:

> For the 5.0.0 release, we should change the code in {{dev/releasepost-03-website.sh}} to include commits, contributors, and changes to the official {{apache/arrow-rs}} and {{apache/arrow-datafusion}} repos. This is import to ensure that the contributions to Rust, DataFusion, and Ballista are recognized in our release notes and blog posts going forward.

Which seems like a very good idea. @andygrove  / @jorgecarleitao  / @Dandandan  do we have any thoughts / plans regarding release notes at this time?

**Comment by jorgecarleitao** [comment]
I will have a take on this one. 👍

**Comment by ianmcook** [comment]
The changelog generator added in #289 looks good, thanks!

We would like to link to this apache/arrow-rs changelog from the apache/arrow release notes. We would also like to include the apache/arrow-rs and apache/arrow-datafusion contributors and contribution counts so that these Rust contributions continue to be properly recognized there. @thisisnic is working to do this in https://github.com/apache/arrow/pull/10774. @alamb or @jorgecarleitao could you reply to Nic's question there? Thanks!

**Comment by alamb** [comment]
Hi @ianmcook  -- thank you for following up. I responded at https://issues.apache.org/jira/browse/ARROW-12701?focusedCommentId=17385759&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17385759
