### ISSUE TITLE
bitwise: support left/right shift using the native wrapping api

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2741]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The current of rust
https://doc.rust-lang.org/std/num/struct.Wrapping.html#

`wrapping_shl` and `wrapping_shr` is not stable.

the shift bit must be u32 data type

part of https://github.com/apache/arrow-rs/issues/2702

Now we just implement this use `value.wrapping_shl(u32)`, after the feature is stable, we can replace them.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
As part of https://github.com/apache/arrow-datafusion/pull/6098 I found this ticket. It turns out DataFusion has these functions implemented:


https://github.com/apache/arrow-datafusion/blob/655f2a84d86a45267ecdfde1860d3748309f270f/datafusion/physical-expr/src/expressions/binary/kernels.rs#L93-L239

Thus I think it would be fairly straightforward to implement shl and shr in arrow-rs by using the DataFusion implementations and following the example of the existing kernels in https://docs.rs/arrow/latest/arrow/compute/kernels/bitwise/fn.bitwise_or.html

The tricky bit will be to cast the arguments to u32 (rather than use the same primitive type)

Marking this is a good first issue as the patterns are relatively set

**Comment by Weijun-H** [comment]
If nobody is currently working on this, I would be happy to take it on.
