### ISSUE TITLE
socks5 proxy support for the object_store crate

### ISSUE THREAD

**Issue by sum12** [apache/arrow-rs#2989]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

object_store crate cannot be used when the application is supposed to be running behind a proxy, as there is no way to configure proxies are common in business envs, reducing the usability of this crate in those envs.

**Describe the solution you'd like**

the underlying reqwest crate (used atleast for aws client) supports use of proxy but the object_store crate currently has no way to configuring that proxy. So the object_store crate can be extended to accept and pass the proxy information while creating the object store. (I havent if other object stores can be made to use proxy, but aws definitely can be extended)

**Describe alternatives you've considered**

**Additional context**

this issues is to gather interest and also feedback

**Comment by tustvold** [comment]
I think adding support for specifying a socks5 proxy makes sense to me, and all the remote object stores make use of the same underlying client, so this should be consistently possible.

One thing to note is we have avoided exposing the reqwest in the public API, so that we can theoretically change it down the line should we wish to. It should be possible to avoid needing to expose this, e.g. by adding a builder method that accepts a socks proxy Url.

**Comment by tustvold** [comment]
All 3 have builders?

https://docs.rs/object_store/latest/object_store/?search=Builder

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2989](https://github.com/apache/arrow-rs/issues/2989)
