### ISSUE TITLE
Support GCP Workload Identity

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3490]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the object_store crate only supports obtaining credentials using a provided service account, it would be beneficial if it could also optionally obtain credentials from its environment. This would be consistent with the behaviour of the aws and azure implementations, and avoids requiring users to handle sensitive long-term service account credentials.

**Describe the solution you'd like**

If no service account is specified, it should fallback to trying to get credentials from a metadata endpoint. 

This is documented [here](https://cloud.google.com/docs/authentication/get-id-token#metadata-server)

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
FYI @scsmithr not sure if this is functionality that would interest you

**Comment by scsmithr** [comment]
Definitely interested in this functionality. I won't be able to pick this up in the short term though.

If it helps, the Go implementation for this is pretty straightforward: https://github.com/golang/oauth2/blob/master/google/default.go#L114

I would also recommend using the metadata IP directly instead of relying on DNS. I've been bitten with flaky DNS resolution on GCP in the past. The IP, along with the `OnGCE` check can be found here: https://github.com/googleapis/google-cloud-go/blob/main/compute/metadata/metadata.go#L39. It's not documented clearly in the code, but this will also work with recent GKE deloyments (see https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity#metadata_server).

**Comment by winding-lines** [comment]
I am wondering if using `application_default_credentials` could also be added as part of this effort - or maybe it's already part of the requirement?
