### ISSUE TITLE
Inconsistent Behaviour Listing File

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3712]
**Describe the bug**

Calling list with a path to an existing file behaves inconsistently

* LocalFileSystem, GCP, AWS, Azure return an empty list
* MemoryStore and HttpStore return the file at the given path

**To Reproduce**

Add the below to the put_get_delete_list_opts test
```
let content_list = flatten_list_stream(storage, Some(&location)).await.unwrap();
assert_eq!(content_list, &[]);
```

**Expected behavior**

The docs state

> Prefixes are evaluated on a path segment basis

As such all stores should return an empty list

**Additional context**

**Comment by roeap** [comment]
It seems azure Gen2 accounts also have the bug.

I'd be happy to take this up. Just a quick question as to how. I would have gone the naive way and just filter results for the affected stores, since I assume we cannot do much about the returns we are getting from the backend.

Do you see another way?

**Comment by tustvold** [comment]
> It seems azure Gen2 accounts also have the bug.

Sigh... I don't understand why Azure thought directories in object storage were a good idea...

> I'd be happy to take this up

I'm actually most of the way through a fix for HTTP and MemoryStore, I'll finish this up and then perhaps you could pick up the azure shenanigans?

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3712](https://github.com/apache/arrow-rs/issues/3712)
