### ISSUE TITLE
Read temporal values from JSON

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#38]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-4803

Ability to parse strings that look like timestamps to timestamp type. Need to consider whether only timestamp type should be supported as most JSON libraries stick to ISO8601. It might also be inefficient to use regex for timestamps, so the user should provide a hint of which columns to convert to timestamps

**Comment by sum12** [comment]
It seems the behavior here is not consistent.  TemporalValues can get parsed to `u64` if they look like `u64` otherwise it is a `null`, but only while dealing with `build_struct_array` whereas for `build_nested_list_array` an error is returned. 

It could be done as done in csv_reader with regex and extra strings describing possible formats. Or we could have parser as closures (eg : `Fn(String) -> Type)`) stored in the reader/decoder(/Schema?)

**Comment by sum12** [comment]
@alamb I would like to take a stab at this one (if it is still relevant)
Thanks for looking :-)

**Comment by alamb** [comment]
As @nevi-me  filed the original ticket, he may have some additional context. Thanks @sum12 !

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/3835
