### ISSUE TITLE
Consider looking into Apache OpenDAL as an alternative to object_store

### ISSUE THREAD

**Issue by chitralverma** [apache/arrow-rs#3888]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I recently checked out [Apache OpenDAL](https://github.com/apache/incubator-opendal) which is written in rust, is async using tokio and exposes a bunch of stores as `services` beyond AZ, GCS and S3. It is also exposed as python and node bindings.

Since this is exactly what `object_store` crate does as well, I was thinking if it makes sense to have 2 identical projects doing basically the same thing?

**Describe the solution you'd like**
My suggestion here is to check out the OpenDAL, and compare its capabilities/ roadmap to object_store. This can potentially help the arrow to not maintain the object_store create and arrow can rely on OpenDAL - if the project makes sense for usecases.

**Note:** Apache OpenDAL is still incubating, but has been around for over a year atleast.

**Describe alternatives you've considered**

**Additional context**
The OpenDAL team has done some initial analysis on this already and has published their thoughts [here](https://docs.rs/opendal/0.30.2/opendal/docs/comparisons/vs_object_store/index.html).

**Comment by Xuanwo** [comment]
Hi, I'm one of the OpenDAL Committers. Thanks for raising this issue. The most recent comparisons of opendal vs object_store could be found [here](https://opendal.apache.org/docs/rust/opendal/docs/comparisons/vs_object_store/index.html).

Our community is currently developing `object_store_opendal` (available at https://github.com/apache/incubator-opendal/tree/main/bindings/object_store), which utilizes `opendal` as the underlying storage implementation. Although it is still in its early stages and quite basic, we are actively working on improving it.

```rust
async fn test_basic() {
    let op = Operator::new(services::Memory::default()).unwrap().finish();
    let object_store: Arc<dyn ObjectStore> = Arc::new(OpendalStore::new(op));

    // Retrieve a specific file
    let path: Path = "data/test.txt".try_into().unwrap();

    let bytes = Bytes::from_static(b"hello, world!");
    object_store.put(&path, bytes).await.unwrap();

    let meta = object_store.head(&path).await.unwrap();

    assert_eq!(meta.size, 13)
}
```

It is possible to simplify the `object_store` interface and use opendal as its underlying implementation. I am willing to assist with any necessary support work.

**Comment by yjshen** [comment]
I had a positive experience using OpenDAL bindings with the object_store. We previously used DataFusion and the object_store API to access HDFS data in our internal project but are now transitioning to MinIO as underlying storage. Initially, I encountered some issues with the default S3 implementation in object_store, but turning to OpenDAL's object_store binding quickly resolved these issues, resulting in seamless MinIO data access. Kudos to @Xuanwo!

It would be fantastic to see either of the suggested approaches implemented: having arrow-rs rely on OpenDAL directly or maintaining the object_store API while using OpenDAL under the hood.

**Comment by Xuanwo** [comment]
> * We should preserve the API that places object store semantics first

I agree with you. That's why I propose to keep `object_store`'s API unchanged at first.

> * We should keep the dependency footprint down

Makes sense, OpenDAL also has plans to split existing services into different features. (We used to enable all http-based services by default because they have almost the same deps list).

> * Continue to support the various auth options we do currently, including the more esoteric GCP and AWS techniques

Of course! OpenDAL already supports most auth options as `object_store`, the only missing picture so far is https://github.com/apache/incubator-opendal/issues/1703. Apart from that, OpenDAL supports `AssumeRole` and `AssumeRoleWithWebIdentity`.

> Personally it seems more sensible to unify the other way round, port any missing functionality to object_store and use it as the underlying implementation of the more generic OpenDAL.

This seems a heavy work because OpenDAL already have 20+ native services supports.

---

My current plan is:

`object_store` side:

- No change any existing code
- Starting from adding `webhdfs` or `oss` (Aliyun's native API support allows users to authenticate with RAM)

`opendal` side:

- Split services in features to avoid include any not needed dependences.

We can integrate `opendal` with `object_store` first and then explore the future possibilities.

**Comment by tustvold** [comment]
> This seems a heavy work because OpenDAL already have 20+ native services supports.


Could we use object_store for the object store implementations in OpenDAL? I.e. object_store becomes a common abstraction for interaction with object stores, and OpenDAL then extends this to other data stores?

**Comment by alamb** [comment]
> It is possible to keep the object_store interface and use opendal as its underlying implementation. I am willing to assist with any necessary support work.

I think this would be a great first step (aka implement the object_store API using opendal)  as it provides a migration path.

Perhaps once that is in place then we can figure out what to do with the existing `object_store` implementations like `S3`, etc.

**Comment by chitralverma** [comment]
wow, thanks everyone for all the constructive. 
great to see so much interest from the community. 🙂

**Comment by tustvold** [comment]
> Perhaps once that is in place then we can figure out what to do with the existing object_store implementations like S3, etc.

I think it would be important to preserve the current public APIs, including the builders, etc..., but see no issue with potentially swapping out their implementations under-the-hood to be something based on OpenDAL. 

Preserving the current APIs would achieve the following:

* Minimise downstream breaking changes, things like the config system have taken many iterations to hash out
* Allow running test suites to ensure consistent handling of things like directories, invalid paths, put atomicity, etc...
* Avoid functionality regressions, e.g. authentication support, [RetryConfig](https://docs.rs/object_store/latest/object_store/struct.RetryConfig.html), [ClientOptions](https://docs.rs/object_store/latest/object_store/struct.ClientOptions.html), [environment config](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env), [options config](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.try_with_options), etc...

I do think it will potentially be less effort to make OpenDAL use object_store instead of the other way round, but I leave that decision to the people undertaking the work :smile:

**Comment by Xuanwo** [comment]
Hi, @tustvold! Thank you for your kind comments! I agree with most of your ideas. Do you think it's a good idea to start with adding a new service support (like `webhdfs` or `oss`)? I'm willing to have a try.

**Comment by r4ntix** [comment]
> I believe the conclusion from https://github.com/apache/arrow-rs/issues/2777 was that the current S3 support already supports communicating with Aliyun Object Storage, but I am happy to be corrected on this, I'm not at all familiar with Alibaba Cloud 😅
@tustvold I am sure that `object_store` is already able to access OSS through S3 compatibility mode, in fact we have already used it in the internal production environment 😄. At the same time, I also saw that `OpenDAL` provides a native way to access OSS @Xuanwo 👍. Nice to see `object_store` and `OpenDAL` working on this.

**Comment by Xuanwo** [comment]
> I am sure that `object_store` is already able to access OSS through S3 compatibility mode, in fact we have already used it in the internal production environment .

Yes, it is possible to access OSS through S3 compatibility mode. However, users cannot authenticate the request using RAM (Aliyun's IAM), which means they are unable to use `assume_role` or `assume_role_web_token` as an alternative to static ak/sk. It's off-topic to discuss the differences between OSS's native and S3 APIs here :laughing:.

Anyways, it sounds great to begin with supporting `webhdfs`! I'll start working on it :rocket:

**Comment by tustvold** [comment]
I've tried to articulate in https://github.com/apache/arrow-rs/pull/4978 what I see as the vision of the object_store crate, and in particular how this might differ from crates such OpenDAL PTAL that are more filesystem-centric in the APIs they expose.

**Comment by helmiazizm** [comment]
> > I believe the conclusion from #2777 was that the current S3 support already supports communicating with Aliyun Object Storage, but I am happy to be corrected on this, I'm not at all familiar with Alibaba Cloud 😅
> 
> @tustvold I am sure that `object_store` is already able to access OSS through S3 compatibility mode, in fact we have already used it in the internal production environment 😄. At the same time, I also saw that `OpenDAL` provides a native way to access OSS @Xuanwo 👍. Nice to see `object_store` and `OpenDAL` working on this.

Do you mind to share the solution? I've been trying to use Python's Polars to read the data in OSS with S3 protocol and it keeps throwing me authentication error.

**Comment by tustvold** [comment]
> I've been trying to use Python's Polars to read the data in OSS with S3 protocol and it keeps throwing me authentication error.

What have you tried? It should just be a case of overriding the endpoint and providing valid credentials

**Comment by helmiazizm** [comment]
> What have you tried? It should just be a case of overriding the endpoint and providing valid credentials

I tried using polars.scan_csv function which uses object_store parameters. Here's how my code look like:

```
import polars as pl

storage_option = {
    "endpoint": "https://s3.oss-region-endpoint.aliyuncs.com",
    "access_key_id": "myosskeyid",
    "secret_access_key": "myosskeysecret",
    "virtual_hosted_style_request": "true"
}
table_path = "s3://mybucket/my/path/to/file.csv"
pl.scan_csv(
    table_path, storage_options=storage_option
).collect()
```

Assigning virtual hosted style request false returns 403 forbidden error, and assigning it to true returns 404 not found: no body. I assumed that assigning virtual hosted style to true actually enables me to authenticate, but the config still made a mistake on creating the URL for the object. Should have something to do with the OSS signature, but I don't know which other keys [here](https://docs.rs/object_store/latest/object_store/aws/enum.AmazonS3ConfigKey.html) should I tweak.

**Comment by tustvold** [comment]
That looks correct to me and consistent with https://github.com/apache/arrow-rs/issues/3827. A 404 error would indicate that either the path or the bucket you've requested doesn't exist, do either contain spaces or special characters as that can be a common source of this sort of issue? Does the URL it is trying to access look correct?

**Comment by helmiazizm** [comment]
The file path is correct. Tried it using another [library](https://duckdb.org/docs/data/csv/overview.html) that doesn't involve Rust object_store and it works. 

On the other side, omitting `https://` protocol doesn't seem to solve the issue. Adding values to bucket and region parameter doesn't solve it either.

I was thinking that the issue occurred because my implementation didn't use "s3v4" `signature_version`, as demanded by OSS. But looking at others succeeded in #3827 without setting any parameters to "s3v4", I'm not sure anymore. Do you think this is more of Polars' fault or is there really some other config that I missed?

**Comment by tustvold** [comment]
> Do you think this is more of Polars' fault or is there really some other config that I missed?

It couldn't hurt to ask.

Can you confirm the path and bucket contain only ASCII alphanumeric characters, this would eliminate a lot of possibilities.

**Comment by helmiazizm** [comment]
> Can you confirm the path and bucket contain only ASCII alphanumeric characters, this would eliminate a lot of possibilities.

The full path consists of ASCII alphanumeric characters and symbols. The symbols are simple underscores (_) and hyphens (-). Nothing too weird.

**Comment by tustvold** [comment]
That should be fine, the only other thing that comes to mind is the region, but I've no idea if OSS cares about that

**Comment by helmiazizm** [comment]
> Are you including the bucket name in the endpoint you are providing

Still returns the same error even with bucket name included.

I'll try to ask Polars developers for this and mention our conversations here. Thanks.
