### ISSUE TITLE
[Question - object_store] AWS credentials provider

### ISSUE THREAD

**Issue by jfuechsl** [apache/arrow-rs#4301]
**Which part is this question about**
`object_store` crate.

**Describe your question**
The `AmazonS3Builder` implements its own AWS credentials resolution and provisioning (which currently doesn't support ECS environments natively).
AWS SDKs (see [here](https://github.com/awslabs/aws-sdk-rust/blob/d1962fd42d376c5c695877041d2a269fd1fa50cd/sdk/aws-config/src/default_provider/credentials.rs#L25) for the Rust SDK) feature a well defined Credential Provider Chain.

My question is: why does this project not use the official AWS Rust SDK implementation for credentials (and possibly the S3 client implementation)?

**Additional context**

Issue #4283 should fix credentials resolution for ECS runtime environments. However the fix doesn't work, since the provided metadata_endpoint is still used in the context of the EC2 credentials provider which postfixes a `/latest/api/token` path, which breaks credentials resolution for ECS: https://github.com/apache/arrow-rs/blob/77aa8f5b2645a91724048f5c1d644c6b52880028/object_store/src/aws/credential.rs#L429

**Comment by tustvold** [comment]
There is more historical context on https://github.com/apache/arrow-rs/issues/2176 but the high level reason is because using the cloud provider SDKs resulted in significant dependency bloat, inconsistent behaviour w.r.t errors, retries, etc... and missing features.

Its also worth noting the AWS SDK you reference didn't exist when this crate was originally written, we used rusoto instead, and is still marked not suitable for production use.

I was under the impression the ECS credentials were now fixed, albeit not released, but a dependency patch should allow using the fixed version based on git sha? Is there something still not working correctly?

There is also the escape valve of https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_credentials if you wish to source credentials through some other mechanism

**Comment by jfuechsl** [comment]
Understood, thanks for the elaboration.

Unfortunately, I realised that the ECS credentials fix does not work. The reason is that the metadata endpoint is still being used in the context of the EC2 credentials provider `InstanceCredentialProvider`, which further appends a path to the endpoint https://github.com/apache/arrow-rs/blob/ea008922445d84d957cf3f89df793187c22d82d8/object_store/src/aws/credential.rs#L429

A proper fix would need to adapt the credentials resolution logic in `AmazonS3Builder::build` by including a ECS specific provider (thus mirroring the official resolution chain in the AWS SDKs).

**Comment by tustvold** [comment]
Thank you for reporting, I'll get a fix in for you today

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4301](https://github.com/apache/arrow-rs/issues/4301)
