### ISSUE TITLE
Support as_datetime::<DataType::Interval~>

### ISSUE THREAD

**Issue by NiwakaDev** [apache/arrow-rs#4969]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'd like to call `as_datetime::<DataType::Interval~>` to address https://github.com/apache/arrow-datafusion/issues/7097.

Is it possible to return `Some(~)`, not `None`?: 

https://github.com/apache/arrow-rs/blob/03d0505fc864c09e6dcd208d3cdddeecefb90345/arrow-array/src/temporal_conversions.rs#L216

Also, is it possible to uncomment the following lines?:
https://github.com/apache/arrow-rs/blob/03d0505fc864c09e6dcd208d3cdddeecefb90345/arrow-array/src/types.rs#L299-L301

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
A DateTime is a point in time, whereas an interval is not, I'm not entirely sure how this would work?

**Comment by Jefffrey** [comment]
I don't think this is the correct way to go about implementing the `extract(x from interval)` functionality, since as mentioned there isn't a well defined way to convert an interval into a datetime.

Would probably need to modify the existing temporal kernels:

https://github.com/apache/arrow-rs/blob/c57857031fb39559924df56e1c8e5f60a1a6e69a/arrow-arith/src/temporal.rs#L225-L232

To be able to extract from intervals directly, instead of attempting to convert intervals to datetime to then leverage existing functionality of these kernels (which only currently work for datetimes).

That or implement the logic entirely on Datafusion's side.

Note there is an issue on Datafusion repo that relates to this functionality: https://github.com/apache/arrow-datafusion/issues/6327
