### ISSUE TITLE
Improve speed of row converter by skipping utf8 checks

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6058]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Part of https://github.com/apache/arrow-rs/issues/5374

@XiangpengHao implemented optimized row format --> ByteView (StringView / BinaryView) encoding/decoding in https://github.com/apache/arrow-rs/issues/5945 / https://github.com/apache/arrow-rs/pull/6044

It also adds benchmarks so we can test🎉 

However, as mentioned in https://github.com/apache/arrow-rs/pull/6044/files#r1676804033 if we know that the `Row` value was created from valid utf8 values, re-validating utf8 is unnecessary.

**Describe the solution you'd like**

Consider an API that would allow skipping utf8 validation

This would need to be justified by performance benchmarks showing it made a significant difference in performance

**Describe alternatives you've considered**

Perhaps it would be an `unsafe` option on the [RowConverter](https://docs.rs/arrow-row/52.1.0/arrow_row/struct.RowConverter.html)

```rust
let converter = RowConverter::new(...);

// Safety: only decoding Rows that came from valid String arrays
let converter = unsafe {
  converter.with_validate_utf8(false)
}
```

**Additional context**

**Comment by xinlifoobar** [comment]
take

**Comment by xinlifoobar** [comment]
Hi @alamb and @XiangpengHao, I have some observations for this issue.

The uf8 validation only happens when row.config.validate_utf8 is true.

https://github.com/apache/arrow-rs/blob/49840ec0f110da5e9a21ce97affd32313d0b720f/arrow-row/src/lib.rs#L1302C1-L1303C1

The validate_utf8 is only set to true when initialized from a RowParser

https://github.com/apache/arrow-rs/blob/49840ec0f110da5e9a21ce97affd32313d0b720f/arrow-row/src/lib.rs#L781-L788

I find the only usage of `RowParse is here` in `RowConverter` and test, did this mean the validate_utf8 will never set to true in the current implementation of `arrow-rs` and we would have the additional validation?

https://github.com/apache/arrow-rs/blob/49840ec0f110da5e9a21ce97affd32313d0b720f/arrow-row/src/lib.rs#L759

**Comment by XiangpengHao** [comment]
> did this mean the validate_utf8 will never set to true 

That's an excellent observation, I also double checked the RowConverter in DataFusion and also did not find any reference to `.parser()` or `RowParser`, for example in `GroupValuesRows`: https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/aggregates/group_values/row.rs#L74-L80

I think utf-8 is not being validated (and is expected) in DataFusion, so we are not slowed by utf-8 validation. But we probably have to keep that utf-8 check because other users may use `RowParser`

**Comment by alamb** [comment]
Perfect. Thank you for the investigation @xinlifoobar  and the confirmation @XiangpengHao

**Comment by wForget** [comment]
@alamb @XiangpengHao Is utf8 validation in parquet reader necessary? I found a large proportion of `parquet::arrow::buffer::offset_buffer::OffsetBuffer<I>::check_valid_utf8` when profiling datafusion-comet native scan.

![Image](https://github.com/user-attachments/assets/7dcea5fc-bf5f-4576-932a-66846851cede)

**Comment by alamb** [comment]
> [@alamb](https://github.com/alamb) [@XiangpengHao](https://github.com/XiangpengHao) Is utf8 validation in parquet reader necessary? I found a large proportion of `parquet::arrow::buffer::offset_buffer::OffsetBuffer<I>::check_valid_utf8` when profiling datafusion-comet native scan.

I think it depends on how much you trust your input files to be valid. If you trust the files to only contain valid utf8 data, the disabling UTF8 validation is certainly an option

However, I think disabling this check would be somewhat cheating on benchmarks as real systems should be validating all user supplied input for safety. 

Here is a ticket describing the 
- https://github.com/apache/arrow-rs/issues/6701
