### ISSUE TITLE
Empty RecordBatch

### ISSUE THREAD

**Issue by cisaacson** [apache/arrow-rs#6412]
**Which part is this question about**
Flight SQL
**Describe your question**
I am using Arrow Flight SQL with DataFusion. If I have an empty `RecordBatch` as the only object in a result stream (which I ensure includes a schema). A call to `flight_data.next().await` never gets this `RecordBatch`. I have tested directly with DataFusion and it works fine. `flight_data` is of type `FlightRecordBatchStream`. Whenever I do have data in one or more `RecordBatch`es it works fine and we get the data as expected including streaming multiple `RecordBatch`es.

The empty `RecordBatch` is created with `RecordBatch::new_empty(schema)` so this should work.

Any reason why Flight SQL would not return an empty `RecordBatch`? 

I have fully verified this, if I return 1 item in the arrays Arrow Flight SQL returns it, but if it is empty arrays it does not return it. This does seem like a bug.

**Comment by alamb** [comment]
I don't know of any, but it wouldn't surprise me if something optimized away the sending of empty record batchs 

I would first recommend verifying that the output of the stream from datafusion actually has the empty record batch

Perhaps you could use https://docs.rs/futures/latest/futures/prelude/stream/trait.StreamExt.html#method.inspect and print out hte batches coming out of DataFusion 🤔

**Comment by cisaacson** [comment]
@alamb I have already verified directly against DataFusion, the empty `RecordBatch` works fine there, it is only when it goes through flight SQL that it doesn't work. And I did a further test with 1 dummy row (value in each array), that works fine with flight SQL. So there is definitely an issue. I am going to make a test similar to this to reproduce the issue:

`arrow-flight/tests/flight_sql_client.rs`

Once I have that working I'll put an update in the ticket.

**Comment by cisaacson** [comment]
@alamb I learned more about this. I did create a test in `arrow-flight` that returns an empty `RecordBatch`, sure enough it definitely returns it to the client. In looking more I found that the DataFusion `cli` has an empty batch test, if it has an empty set of `RecordBatch`es, it uses the schema to create and return an empty `RecordBatch`. This indicates that DataFusion itself is doing a similar filter. There are many cases with this type of code: `.filter(|b| b.num_rows() > 0)` testing each `RecordBatch`. I'm not sure which one is filtering it out in my case but that must be what is happening. 

The conclusion is that `arrow-flight-sql` is doing exactly the right thing, the issue is in fact in DataFusion.

Based on this I have a relatively easy work-around, similar to how the DataFusion `cli` handles it. I'll close this case now, but if anyone wants to research why DataFusion filters out empty batches, and if that is necessary, it would be good to know.

**Comment by alamb** [comment]
> Based on this I have a relatively easy work-around, similar to how the DataFusion cli handles it. I'll close this case now, but if anyone wants to research why DataFusion filters out empty batches, and if that is necessary, it would be good to know.

I suspect it was probably some optimization (e.g. sending empty record batches over the network is wasteful -- that is unless it is the *ONLY* record batch that would be sent)

**Comment by cisaacson** [comment]
@alamb Thanks, makes sense. At any rate I have a workaround, it would probably be an impactful change in DataFusion. Your idea to create a test is what led me to what was really happening, thanks for that.

**Comment by gruuya** [comment]
I'm not convinced that this issue has actually been resolved (or at least I need to open a new one?).

Basically, I'd like to be able to round-trip a lonely empty record batch, for the purpose of creating a table in advance for some actual up-coming data, but that doesn't work atm:
```rust
    #[tokio::test]
    async fn test_empty_batch_round_trip() {
        let schema = Schema::new(vec![Field::new("data", DataType::Int32, false)]);
        let empty_batch = RecordBatch::new_empty(Arc::new(schema));
        let stream = FlightDataEncoderBuilder::new()
            .build(futures::stream::iter(vec![Ok(empty_batch.clone())]));

        let data: Vec<RecordBatch> = FlightRecordBatchStream::new_from_flight_data(stream)
            .try_collect()
            .await
            .unwrap();

        assert_eq!(data, vec![empty_batch]);
    }
```
This test currently fails, as the decoded data vector is empty.

I've identified the issue to be in `split_batch_for_grpc_response` which for an empty record batch returns no batch to be queued up (instead of that sole batch), so the fix seems pretty simple https://github.com/apache/arrow-rs/pull/7188

**Comment by alamb** [comment]
> Basically, I'd like to be able to round-trip a lonely empty record batch, for the purpose of creating a table in advance for some actual up-coming data, but that doesn't work atm:

If the usecase is to send the schema information before any data, perhaps you can use 

https://docs.rs/arrow-flight/latest/arrow_flight/encode/struct.FlightDataEncoderBuilder.html#method.with_schema

I looked at the code and that looks like it will send the schema information immediately (even before any record batches are sent): 
https://docs.rs/arrow-flight/latest/src/arrow_flight/encode.rs.html#318-320

**Comment by gruuya** [comment]
Thanks! I did try that first, though only with `FlightRecordBatchStream`, which doesn't output the single empty batch (nor the schema). The first `FlightData` is the schema which it skips
https://github.com/apache/arrow-rs/blob/d54a8c67d5b8006ee0cf6adf16821c4d2a6f7026/arrow-flight/src/decode.rs#L185-L187
and the second `FlightData` is missing, since `FlightDataEncoder` didn't enqueue it (as shown in #7188). Consequently an empty vector is returned.

That said it should be possible to use the lower-level `FlightDataDecoder` to achieve this by making a custom stream wrapper around it, will try it out now.

Nonetheless, it may be worthwhile to have the empty batch handling work in this singleton mode via the default decoder (`FlightRecordBatchStream`).

**Comment by gruuya** [comment]
In the end I managed to reconstruct an empty batch using `FlightRecordBatchStream` alone, as described [here](https://github.com/apache/arrow-rs/pull/7188#issuecomment-2681061340), thanks!
