### ISSUE TITLE
Add a lint to automatically check for unused dependencies

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6796]
Perhaps we could enable a lint to test for this?

_Originally posted by @tustvold in https://github.com/apache/arrow-rs/pull/6792#pullrequestreview-2459473603_

**Comment by findepi** [comment]
for context, in the past i tried using cargo machete, but was disappointed by false positives (maybe because i run it on a complex project). For https://github.com/apache/arrow-rs/pull/6792 i used RustRover's builtin capabilities. But even then I had to solve false positives manually. In https://github.com/apache/datafusion/pull/13541 there was also one false positive (apparently due to an imperfectly implemented macro / limitation in RR -- depending on how we look at it)

I wish I knew how to make this automated.

**Comment by tustvold** [comment]
unused_crate_dependencies is a lint that can be enabled at the workspace level

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6792

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6792
